name: Update nixpkgs
on:
  schedule:
    - cron:  '0 20 3 * *'
jobs:
  niv-updater:
    name: 'Create PRs for updating nixpkgs'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          whitelist: 'nixpkgs'
