name: Update dependencies
on:
  schedule:
    - cron:  '0 5 * * 4'
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
